version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: punthisa
      POSTGRES_PASSWORD: se2024
      POSTGRES_DB: se_challenge
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: db
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: se_challenge
      TYPEORM_SYNCHRONIZE: true
      TYPEORM_ENTITIES: dist/**/*.entity.js
    depends_on:
      - db
    ports:
      - '3001'

  frontend:
    build:
      context: ./frontend
    ports:
      - '4200'
    depends_on:
      - backend

volumes:
  postgres_data:
